### ISSUE TITLE
Feature request: save original icon before badging and add command to revert to original icon

### ISSUE THREAD

**Issue by esusatyo** [HazAT/badge#1]
This is a great tool! How hard would it be to save the original icons somewhere (preferably hidden, so does not mess with git repo), and then add a command like `badge --revert` to go back to the original icon?

**Comment by jeeftor** [comment]
This is where you want to use git - and you can revert the image assets afterwards.

**Comment by HazAT** [comment]
pretty much what @jeeftor said ... sorry wontfix
