### ISSUE TITLE
crash in MiniMagick::Invalid on jenkins

### ISSUE THREAD

**Issue by jtligon** [HazAT/badge#10]
running on jenkins

>/usr/local/bin/badge --shield "0.2.3-156"

crash report c53836f88f90e92fb2a6aad1530badd5

I've triple checked that ImageMagick(6.9.3-0) and GraphicsMagick(1.3.23) ARE installed 

>/usr/local/lib/ruby/gems/2.2.0/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:200:in `rescue in validate!': [!] ImageMagick/GraphicsMagick is not installed (MiniMagick::Invalid)

**Comment by HazAT** [comment]
Did you try to run add this to your `PATH` in Jenkins?

`PATH=$PATH:/usr/local/bin`

**Comment by jtligon** [comment]
I did, and that moved me on to a new error, which is my inexperience with shield.io

Thanks @HazAT
