### ISSUE TITLE
Fastlane action incorrect behaviour when setting glob value.

### ISSUE THREAD

**Issue by lalkrishna** [HazAT/badge#106]
Fastlane action:
`add_badge(shield: "Version-0.0.3-blue", no_badge: true, shield_scale: "0.75", glob: "/../Assets\ test/*.appiconset/*.{png,PNG}")`
changes files in `./../Assets test/AppIcon.appiconset/` directory.

But the same action worked as expected:
`badge --shield "Version-0.0.5-blue" --dark  --shield_scale 0.75 —glob "/../Assets\ test/*.appiconset/*.{png,PNG}"`

**Comment by bukira** [comment]
changes files in ./../Assets test/AppIcon.appiconset/ directory. <--- do you mean DOESNT change? as this doesn't work for me says
 _"Could not find any app icons..."_

**Comment by HazAT** [comment]
yeah I know this is a bit confusing but changing this will break more now.
