### ISSUE TITLE
--no_badge not working

### ISSUE THREAD

**Issue by justdan0227** [HazAT/badge#115]
So I added a badge and with 

badge --alpha
badge --shield "Version-0.0.3-blue"

and want to remove all badges with 
badge --no_badge

However getting:

$ badge --no_badge
Ignoring racc-1.5.2 because its extensions are not built. Try: gem pristine racc --version 1.5.2
[13:42:07]: Start adding badges...
[13:42:07]: Did nothing... Enable --verbose for more info.

**Comment by justdan0227** [comment]
So I see that you can use git checkout -- Assets.xcassets, however what if you update your assets and then need to revert

**Comment by HazAT** [comment]
--no_badge is not meant to remove existing badges, it just doesn't add beta/alpha.
You need to use git for that if you want to revert. Badge is designed to run on a CI where the changes to the icon are lost.
