### ISSUE TITLE
New feature: any image

### ISSUE THREAD

**Issue by bartoszj** [HazAT/badge#13]
Hi,

First of all, thanks for this great tool. But it would be nice If this tool could add badge to any image from any place, not only app icon. I thought, if you can add `path` parameter which will be a path to the image, or list / array of paths to images. Or maybe path to directory with images to replace.

**Comment by HazAT** [comment]
Already there ... Look at the `glob` parameter

**Comment by bartoszj** [comment]
😍. Great, I'll test it tomorrow. Thanks a lot and sorry for confusion.
