### ISSUE TITLE
Lack of dependencies

### ISSUE THREAD

**Issue by Gimungagap** [HazAT/badge#20]
Mac OS, iOS test project.
I've installed the gem:

`sudo gem install badge`

Navigated to a folder of a test ios project and executed a command:

`badge`

Got an error:

> [19:53:39]: Start adding badges...
> [19:53:39]: './gitlab-ci-test/Images.xcassets/AppIcon.appiconset/1.png'
> -------------------------------------------------------------------------------------------
> 😨  An error occured. Please enable crash reports using fastlane enable_crash_reporting.
> 👍  This makes resolving issues much easier and helps improve fastlane.
> 🔒  The reports will be stored securely on getsentry.com.
> 🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
> -------------------------------------------------------------------------------------------
> /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.2/lib/mini_magick/image.rb:200:in rescue in validate!': [!] ImageMagick/GraphicsMagick is not installed (MiniMagick::Invalid)
> 
> 	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.2/lib/mini_magick/image.rb:198:in validate!'
> 	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.2/lib/mini_magick/image.rb:113:in block in create'
> 	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.2/lib/mini_magick/image.rb:112:in tap'
> 	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.2/lib/mini_magick/image.rb:112:in create'
> 	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.2/lib/mini_magick/image.rb:34:in read'
> 	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.2/lib/mini_magick/image.rb:90:in block in open'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:36:in open'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:36:in open'
> 	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.2/lib/mini_magick/image.rb:89:in open'
> 	from /Library/Ruby/Gems/2.0.0/gems/badge-0.4.0/lib/badge/runner.rb:112:in add_badge'
> 	from /Library/Ruby/Gems/2.0.0/gems/badge-0.4.0/lib/badge/runner.rb:43:in block in run'
> 	from /Library/Ruby/Gems/2.0.0/gems/badge-0.4.0/lib/badge/runner.rb:36:in each'
> 	from /Library/Ruby/Gems/2.0.0/gems/badge-0.4.0/lib/badge/runner.rb:36:in run'
> 	from /Library/Ruby/Gems/2.0.0/gems/badge-0.4.0/bin/badge:53:in block (2 levels) in run'
> 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in call'
> 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in call'
> 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in run'
> 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in run_active_command'
> 	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.42.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in run!'
> 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in run!'
> 	from /Library/Ruby/Gems/2.0.0/gems/badge-0.4.0/bin/badge:57:in run'
> 	from /Library/Ruby/Gems/2.0.0/gems/badge-0.4.0/bin/badge:63:in top (required)'
> 	from /usr/local/bin/badge:23:in load'
> 	from /usr/local/bin/badge:23:in main

Tried to install ImageMagick and GraphicsMagick:

`sudo gem install image_magick`

> Fetching: image_magick-0.1.9.gem (100%)
> Successfully installed image_magick-0.1.9
> Parsing documentation for image_magick-0.1.9
> Installing ri documentation for image_magick-0.1.9
> Done installing documentation for image_magick after 0 seconds
> 1 gem installed

`sudo gem install graphicsmagick`

> Fetching: graphicsmagick-1.0.5.gem (100%)
> Successfully installed graphicsmagick-1.0.5
> Parsing documentation for graphicsmagick-1.0.5
> Installing ri documentation for graphicsmagick-1.0.5
> Done installing documentation for graphicsmagick after 0 seconds
> 1 gem installed

The error still the same.
What am I doing wrong?

**Comment by HazAT** [comment]
possible duplicate https://github.com/HazAT/badge/issues/23

**Comment by HazAT** [comment]
Please update badge to 0.4.1

**Comment by danielpetroianu** [comment]
Issue still reproduces.
I've uninstalled badge and it's dependencies, and reinstalled badge v 0.4.1, and the same error occurs.
I'm I the only one?

**Comment by HazAT** [comment]
Can you check you environment for the PATH var

it should contain `PATH=$PATH:/usr/local/bin` otherwise it will not find imagemagick

**Comment by danielpetroianu** [comment]
/usr/local/bin is in $PATH. Also installed badge with sudo. Same result as above.

**Comment by danielpetroianu** [comment]
As the error states, `ImageMagick/GraphicsMagick is not installed` on my machines.
This is not a bug for `badge`, but it does not state in the documentation steps to install this dependencies.

[minimagick](https://github.com/minimagick/minimagick) states [`ImageMagick or GraphicsMagick command-line tool has to be installed.`](https://github.com/minimagick/minimagick#requirements)

Maybe the readme should state this.

**Comment by HazAT** [comment]
OK ... so now it works for you?

**Comment by danielpetroianu** [comment]
Yes. @Gimungagap can you try as well? 
Are there any quarks with this steps:
# brew install imagemagick
# gem install badge [if not already installed]
# run badge

**Comment by Gimungagap** [comment]
@danielpetroianu yup, that fixes the issue. Thanks a lot.
I also tried MiniMagick installation via gems and that didn't solve the problem but brew installation did the trick.
