### ISSUE TITLE
Throwing 520 origin error

### ISSUE THREAD

**Issue by gapl** [HazAT/badge#21]
When using badge with a custom shield without a beta badge, I am getting an error thrown randomly.

It's very sporadic, but errors my lane quite often.

The error thrown is `520 Origin Error`.

**Comment by dozzman** [comment]
Having the same issue here, seems like its only happening in a lane, since when i run 'fastlane run badge' it works every time.

**Comment by HazAT** [comment]
shield.io is not a very good service ... added failsafe and retry mechanisms to prevent errors.

Please update badge to 0.4.1 ... this version should fix all your errors.
