### ISSUE TITLE
Proxy?

### ISSUE THREAD

**Issue by fuggly** [HazAT/badge#40]
Hiyas

I'm kind new to this, so I apologize in advance if I ask a stupid question here, but to be able to use badge with --shield over a proxy, what would I need to do so that fetching from shield.io works over the proxy?

**Comment by jamesdaniels** [comment]
Now that badge is using curb, you can use the environment variables that curl will respect

```http_proxy [protocol://]<host>[:port]
HTTPS_PROXY [protocol://]<host>[:port]
[url-protocol]_PROXY [protocol://]<host>[:port]
ALL_PROXY [protocol://]<host>[:port]
NO_PROXY <comma-separated list of hosts>
```

via curl's manpage

**Comment by jamesdaniels** [comment]
This should satisfy the issue, @HazAT feel free to close.

**Comment by HazAT** [comment]
💯
