### ISSUE TITLE
0.8.0 MiniMagick::Invalid at jenkins

### ISSUE THREAD

**Issue by Tobrek** [HazAT/badge#42]
After updating badge to 0.8.0 we get the following error at Jenkins:
fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

/Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:204:in `rescue in validate!': [!] `identify /var/folders/w1/cs2bv4md13s7ksh38yvc7crw000088/T/mini_magick20170314-30338-zm1o7x.png` failed with error: (MiniMagick::Invalid)
identify: improper image header `/var/folders/w1/cs2bv4md13s7ksh38yvc7crw000088/T/mini_magick20170314-30338-zm1o7x.png' @ error/png.c/ReadPNGImage/4364.

        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:202:in `validate!'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:113:in `block in create'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:112:in `tap'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:112:in `create'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:34:in `read' 
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:90:in `block in open'
        from /Users/Jenkins/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:36:in `open' 
        from /Users/Jenkins/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:36:in `open' 
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:89:in `open' 
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/badge-0.8.1/lib/badge/runner.rb:99:in `add_shield'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/badge-0.8.1/lib/badge/runner.rb:65:in `block in run'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/badge-0.8.1/lib/badge/runner.rb:54:in `each' 
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/badge-0.8.1/lib/badge/runner.rb:54:in `run'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane/lib/fastlane/actions/badge.rb:19:in `run'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:243:in `block (2 levels) in execute_action'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:221:in `block in execute_action'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:217:in `chdir'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:217:in `execute_action'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:139:in `trigger_action_by_name'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
        from Fastfile:53:in `block (2 levels) in parsing_binding'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane/lib/fastlane/lane.rb:33:in `call' 
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane/lib/fastlane/lane.rb:33:in `call' 
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/commander-4.4.3/lib/commander/command.rb:178:in `call' 
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/commander-4.4.3/lib/commander/command.rb:178:in `call' 
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!' 
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!' 
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/bin/fastlane:15:in `<top (required)>'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `load' 
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `<main>'
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval' 
        from /Users/Jenkins/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

Did i miss an updated dependency?

**Comment by HazAT** [comment]
Can you please run it with `--verbose` and send me the output. Just want to be able to reproduce it.
Also check if you have `rsvg-convert` installed (which you probably have).

**Comment by Tobrek** [comment]
rsvg-convert is installed with version 2.40.16

Output of 
badge --shield "Version-1.2-green" --verbose --glob "/**/mipmap*/*.{png,PNG}"
is:
[14:08:26]: Start adding badges...
[14:08:26]: './build/intermediates/res/merged/debug/mipmap-hdpi/ic_launcher.png'
[14:08:27]: './build/intermediates/res/merged/debug/mipmap-hdpi/ic_launcher.png'
[14:08:27]: './build/intermediates/res/merged/debug/mipmap-mdpi/ic_launcher.png'
[14:08:27]: './build/intermediates/res/merged/debug/mipmap-mdpi/ic_launcher.png'
Error reading SVG:Error opening file /Users/Jenkins/my_project/app/Version-1.2-green.svg: No such file or directory


Looking for related GitHub issues on fastlane/fastlane...

/Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:204:in `rescue in validate!': [!] `identify /var/folders/w1/cs2bv4md13s7ksh38yvc7crw000088/T/mini_magick20170314-39933-oqne0x.png` failed with error: (MiniMagick::Invalid)
identify: improper image header `/var/folders/w1/cs2bv4md13s7ksh38yvc7crw000088/T/mini_magick20170314-39933-oqne0x.png' @ error/png.c/ReadPNGImage/4364.

	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:202:in `validate!'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:113:in `block in create'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:112:in `tap'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:112:in `create'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:34:in `read'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:90:in `block in open'
	from /Users/Jenkins/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:36:in `open'
	from /Users/Jenkins/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:36:in `open'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:89:in `open'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/badge-0.8.1/lib/badge/runner.rb:99:in `add_shield'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/badge-0.8.1/lib/badge/runner.rb:65:in `block in run'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/badge-0.8.1/lib/badge/runner.rb:54:in `each'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/badge-0.8.1/lib/badge/runner.rb:54:in `run'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/badge-0.8.1/lib/badge/commands_generator.rb:34:in `block (2 levels) in run'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/fastlane-2.19.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/badge-0.8.1/lib/badge/commands_generator.rb:39:in `run'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/badge-0.8.1/lib/badge/commands_generator.rb:11:in `start'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/gems/badge-0.8.1/bin/badge:7:in `<top (required)>'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/bin/badge:23:in `load'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/bin/badge:23:in `<main>'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Jenkins/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by carlosefonseca** [comment]
I'm hitting the same problem…


```
❯❯❯ fastlane --verbose run badge shield:"abc-123-995533"
DEBUG [2017-03-14 14:41:05.14]: Checking if there are any plugins that should be loaded...
DEBUG [2017-03-14 14:41:05.20]: Using shield: abc-123-995533
INFO [2017-03-14 14:41:05.21]: Successfully loaded custom action […].
INFO [2017-03-14 14:41:05.21]: -------------------
INFO [2017-03-14 14:41:05.21]: --- Step: badge ---
INFO [2017-03-14 14:41:05.21]: -------------------
INFO [2017-03-14 14:41:05.35]: gem 'badge' is already installed
DEBUG [2017-03-14 14:41:05.49]: Verbose active...
DEBUG [2017-03-14 14:41:05.49]: Parameters: {:dark=>nil, :custom=>nil, :no_badge=>nil, :shield=>"abc-123-995533", :alpha=>nil, :shield_io_timeout=>nil, :glob=>nil, :alpha_channel=>nil, :shield_gravity=>nil, :shield_no_resize=>nil}
INFO [2017-03-14 14:41:05.49]: Start adding badges...
DEBUG [2017-03-14 14:41:05.49]: Trying to load image from shield.io. Timeout: 10s
DEBUG [2017-03-14 14:41:05.49]: URL: https://img.shields.io/badge/abc-123-995533.svg
INFO [2017-03-14 14:41:06.30]: './path/app_icon_xpto.xcassets/AppIcons.appiconset/icon_29.png'
DEBUG [2017-03-14 14:41:06.30]: Adding badge image ontop of icon
INFO [2017-03-14 14:41:06.37]: './path/app_icon_xpto.xcassets/AppIcons.appiconset/icon_29.png'
DEBUG [2017-03-14 14:41:06.37]: Adding shield.io image ontop of icon
INFO [2017-03-14 14:41:07.11]: './path/app_icon_xpto.xcassets/AppIcons.appiconset/icon_29@2x.png'
DEBUG [2017-03-14 14:41:07.11]: Adding badge image ontop of icon
INFO [2017-03-14 14:41:07.18]: './path/app_icon_xpto.xcassets/AppIcons.appiconset/icon_29@2x.png'
DEBUG [2017-03-14 14:41:07.18]: Adding shield.io image ontop of icon
Error reading SVG:Error opening file /Users/carlos/.jenkins/workspace/b2c-ios/abc-123-995533.svg: No such file or directory


Looking for related GitHub issues on fastlane/fastlane...
Search query: `identify /var/folders/m7/6xyj63gn1d70p_1qj_0jtblw0000gn/T/mini_magick20170314-75557-1en9rla.png` failed with error:
identify: improper image header `/var/folders/m7/6xyj63gn1d70p_1qj_0jtblw0000gn/T/mini_magick20170314-75557-1en9rla.png' @ error/png.c/ReadPNGImage/3921.

URL: https://api.github.com/search/issues?q=%60identify%20/var/folders/m7/6xyj63gn1d70p_1qj_0jtblw0000gn/T/mini_magick20170314-75557-1en9rla.png%60%20failed%20with%20error:%0Aidentify:%20improper%20image%20header%20%60/var/folders/m7/6xyj63gn1d70p_1qj_0jtblw0000gn/T/mini_magick20170314-75557-1en9rla.png'%20@%20error/png.c/ReadPNGImage/3921.%0A+repo:fastlane/fastlane
ERROR [2017-03-14 14:41:07.74]: Error finding relevant GitHub issues: undefined method `map' for nil:NilClass
/Users/carlos/.gems/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:204:in `rescue in validate!': [!] `identify /var/folders/m7/6xyj63gn1d70p_1qj_0jtblw0000gn/T/mini_magick20170314-75557-1en9rla.png` failed with error: (MiniMagick::Invalid)
identify: improper image header `/var/folders/m7/6xyj63gn1d70p_1qj_0jtblw0000gn/T/mini_magick20170314-75557-1en9rla.png' @ error/png.c/ReadPNGImage/3921.

	from /Users/carlos/.gems/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:202:in `validate!'
	from /Users/carlos/.gems/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:113:in `block in create'
	from /Users/carlos/.gems/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:112:in `tap'
	from /Users/carlos/.gems/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:112:in `create'
	from /Users/carlos/.gems/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:34:in `read'
	from /Users/carlos/.gems/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:90:in `block in open'
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/open-uri.rb:37:in `open'
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/open-uri.rb:37:in `open'
	from /Users/carlos/.gems/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:89:in `open'
	from /Users/carlos/.gems/gems/badge-0.8.1/lib/badge/runner.rb:99:in `add_shield'
	from /Users/carlos/.gems/gems/badge-0.8.1/lib/badge/runner.rb:65:in `block in run'
	from /Users/carlos/.gems/gems/badge-0.8.1/lib/badge/runner.rb:54:in `each'
	from /Users/carlos/.gems/gems/badge-0.8.1/lib/badge/runner.rb:54:in `run'
	from /Users/carlos/.gems/gems/fastlane-2.19.3/fastlane/lib/fastlane/actions/badge.rb:19:in `run'
	from /Users/carlos/.gems/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:243:in `block (2 levels) in execute_action'
	from /Users/carlos/.gems/gems/fastlane-2.19.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/carlos/.gems/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:221:in `block in execute_action'
	from /Users/carlos/.gems/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:217:in `chdir'
	from /Users/carlos/.gems/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:217:in `execute_action'
	from /Users/carlos/.gems/gems/fastlane-2.19.3/fastlane/lib/fastlane/one_off.rb:41:in `run'
	from /Users/carlos/.gems/gems/fastlane-2.19.3/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	from /Users/carlos/.gems/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:191:in `block (2 levels) in run'
	from /Users/carlos/.gems/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/carlos/.gems/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/carlos/.gems/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/carlos/.gems/gems/fastlane-2.19.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/carlos/.gems/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/carlos/.gems/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /Users/carlos/.gems/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/carlos/.gems/gems/fastlane-2.19.3/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
	from /Users/carlos/.gems/gems/fastlane-2.19.3/bin/fastlane:15:in `<top (required)>'
	from /Users/carlos/.gems/bin/fastlane:23:in `load'
	from /Users/carlos/.gems/bin/fastlane:23:in `<main>'
```

**Comment by HazAT** [comment]
I am on it guys, stay tuned

**Comment by HazAT** [comment]
Guys update to `0.8.2` this fixes the issue.

**Comment by Tobrek** [comment]
Thank you. It's running again without problems.
