### ISSUE TITLE
--custom options does not seem to work

### ISSUE THREAD

**Issue by cyrus86** [HazAT/badge#47]
Somehow it still prints "BETA" on the icon, even if I call the options:
`badge --dark --custom "DEV"`

**Comment by HazAT** [comment]
Hey, `--custom` should be used by pointing to an actual file, like this example in the readme.
`--custom "path_to/custom_badge.png"`

**Comment by cyrus86** [comment]
Wow, that should have been obvious to me. thanks for answering and sorry for the trouble!
