### ISSUE TITLE
Shield.io .png occasionally isnt created correctly

### ISSUE THREAD

**Issue by JonathanReid** [HazAT/badge#49]
Sometimes, but not everytime, the .png created from shield.io is corrupt and un openable. I can see the shield .png before its applied to my icons and they can not be opened by my mac.

I get the following output:
`/Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:204:in rescue in validate!': 
[31m[!] identify /var/folders/t0/11ltw64s0jq64t1lbqnk9gw800007x/T/mini_magick20170526-7364-1eogi8k.png failed with error: (MiniMagick::Invalid)

15:29:56 identify: improper image header /var/folders/t0/11ltw64s0jq64t1lbqnk9gw800007x/T/mini_magick20170526-7364-1eogi8k.png' @ error/png.c/ReadPNGImage/4358.

15:29:56 [0m
15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:202:in validate!'

15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:113:in block in create'

15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:112:in tap'

15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:112:in create'

15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:34:in read'

15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:90:in block in open'

15:29:56 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:36:in  open'

15:29:56 	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:36:in  open'

15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:89:in open'

15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/badge-0.8.4/lib/badge/runner.rb:106:in add_shield'

15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/badge-0.8.4/lib/badge/runner.rb:66:in block in run'

15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/badge-0.8.4/lib/badge/runner.rb:55:in each'
15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/badge-0.8.4/lib/badge/runner.rb:55:in run'
15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/badge-0.8.4/lib/badge/commands_generator.rb:34:in block (2 levels) in run'
15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in call'
15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in call'
15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in run'
15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in run_active_command'
15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.26.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in run!'
15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in run!'
15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/badge-0.8.4/lib/badge/commands_generator.rb:39:in run'
15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/badge-0.8.4/lib/badge/commands_generator.rb:11:in start'
15:29:56 	from /Library/Ruby/Gems/2.0.0/gems/badge-0.8.4/bin/badge:7:in <top (required)>'
15:29:56 	from /usr/local/bin/badge:23:in load'
15:29:56 	from /usr/local/bin/badge:23:in <main>'
15:29:57 Build step 'Conditional step (single)' marked build as failure`

This seems to happen for no clear reason, and I can run just the command over and over and see different results each time.

**Comment by kschrage** [comment]
I debugged it a while ago. Seems like shields.io's server gives an error page ("please try again..." instead of a valid png from time to time. After installing librsvg the error doesn't occur anymore because badge now requests svgs which seem to be more stable.

**Comment by JonathanReid** [comment]
yep, installing librsvg has fixed the issue, Badge is now a lot more stable. 

Thanks!
