### ISSUE TITLE
no_badge is not working in android .

### ISSUE THREAD

**Issue by ashutoshsingh33** [HazAT/badge#51]
badge(glob: "/app/src/main/res/mipmap-*dpi/*.{png,PNG}",
      shield: "Version-#{value}-blue",
      no_badge: true)

**Comment by HazAT** [comment]
There is actually no difference for icons between iOS/Android, `badge` just manipulates pngs.
Is it still not working and are the shield on the icon?

**Comment by ashutoshsingh33** [comment]
@HazAT  yes now its working. It fault of my pngs . Thankyou.
