### ISSUE TITLE
badge --glob "res/ios/beta/Appicon/*" does not find any icons

### ISSUE THREAD

**Issue by funkybaboon** [HazAT/badge#52]
I have my icons in the folder `res/ios/beta/Appicon/*`, however badge doesn't find them with the glob option:

```
Benjamins-MBP:trade-ionic ben$ ls res/ios/beta/Appicon/*
res/ios/beta/Appicon/Icon-29@2x.png   res/ios/beta/Appicon/Icon-40@3x.png   res/ios/beta/Appicon/Icon-57@2x.png   res/ios/beta/Appicon/Icon-72.png      res/ios/beta/Appicon/Icon-83.5@2x.png
res/ios/beta/Appicon/Icon-29@3x.png   res/ios/beta/Appicon/Icon-50.png      res/ios/beta/Appicon/Icon-60.png      res/ios/beta/Appicon/Icon-72@2x.png   res/ios/beta/Appicon/icon-29.png
res/ios/beta/Appicon/Icon-40.png      res/ios/beta/Appicon/Icon-50@2x.png   res/ios/beta/Appicon/Icon-60@2x.png   res/ios/beta/Appicon/Icon-76.png
res/ios/beta/Appicon/Icon-40@2x.png   res/ios/beta/Appicon/Icon-57.png      res/ios/beta/Appicon/Icon-60@3x.png   res/ios/beta/Appicon/Icon-76@2x.png
Benjamins-MBP:trade-ionic ben$ badge --verbose --glob "res/ios/beta/Appicon/*"
DEBUG [2017-06-16 11:24:32.50]: Verbose active... VERSION: 0.8.4
DEBUG [2017-06-16 11:24:32.50]: Parameters: {:glob=>"res/ios/beta/Appicon/*", :dark=>nil, :alpha=>nil, :alpha_channel=>nil, :custom=>nil, :no_badge=>nil, :badge_gravity=>nil, :shield=>nil, :shield_io_timeout=>nil, :shield_geometry=>nil, :shield_gravity=>nil, :shield_scale=>nil, :shield_no_resize=>nil}
ERROR [2017-06-16 11:24:32.50]: Could not find any app icons...
```
Why is `--glob` not working here?

**Comment by HazAT** [comment]
I think since this is running in the `fastlane` folder you have to `../res/ios/beta/Appicon/*`

**Comment by funkybaboon** [comment]
I'm not using fastlane here. This is a Ionic 1 project, and the `res/ios/beta/Appicon` folder is where we keep our icons. It would be awesome to use badge here.

```
Benjamins-MBP:trade-ionic ben$ badge --verbose --glob "../res/ios/beta/Appicon/*"
DEBUG [2017-06-29 09:10:29.64]: Verbose active... VERSION: 0.8.4
DEBUG [2017-06-29 09:10:29.65]: Parameters: {:glob=>"../res/ios/beta/Appicon/*", :dark=>nil, :alpha=>nil, :alpha_channel=>nil, :custom=>nil, :no_badge=>nil, :badge_gravity=>nil, :shield=>nil, :shield_io_timeout=>nil, :shield_geometry=>nil, :shield_gravity=>nil, :shield_scale=>nil, :shield_no_resize=>nil}
ERROR [2017-06-29 09:10:29.65]: Could not find any app icons...
```

**Comment by HazAT** [comment]
Oh I see, right, sorry about that.
Just looked at the source code again, the fix is to add a `/`
`badge --verbose --glob "/res/ios/beta/Appicon/*"`
Because I always take the executing path as "root".
`app_icons = Dir.glob("#{path}#{glob}")`
Sorry about the confusion.

**Comment by funkybaboon** [comment]
Ah ok. Now it works. I've extended the documentation to include this info:
https://github.com/HazAT/badge/pull/53

**Comment by elvin-vega** [comment]
@HazAT I'm using badge with glob option. Badge throw a message "Could not find any app icons...". Below is the badge command I'm using:
`badge --shield "Version:-3.5.0.318-blue" --dark true --shield_no_resize true --glob /Users/<HOME_FOLDER>/Dev/source/Images/Images.xcassets/AppIcon.appiconset/*.{png,PNG}" `

I have similar approach in fastfile throw the same message. Below is how I have it configure in fastlane:
`add_badge(`
`        shield: "Version:-3.5.0.318-blue", `
`        dark: true, `
`        shield_no_resize: true, `
`        glob: "/Users/<HOME_FOLDER>/Dev/source/Images/Images.xcassets/AppIcon.appiconset/*.{png,PNG}" `
`      )`

The funny thing is if I copy the app icons at `/Users/<HOME_FOLDER>/Dev/configuredProjects/AppIcon.appiconset` badge and fastlane `add_badge works`. Fastlane root folder located at `/Users/<HOME_FOLDER>/Dev/configuredProjects/fastlane`.

Here example working command:
`badge --shield "Version:-3.5.0.318-blue" --dark true --shield_no_resize true`

`add_badge(`
`        shield: "Version:-3.5.0.318-blue", `
`        dark: true, `
`        shield_no_resize: true, `
`      )`

What's wrong with the `glob` option?
