### ISSUE TITLE
shield_io_timeout being used for retry wait time

### ISSUE THREAD

**Issue by jkirchner** [HazAT/badge#67]
If you include a timeout parameter for the shield IO, it is currently being used for the retry time instead of the timeout.

In the attached screenshot you can see that I passed in a value of 300 (5 minutes) for the timeout parameter, but it is being used for the retry time instead.

![badge_error](https://user-images.githubusercontent.com/1939393/37840434-ad0efdec-2e82-11e8-9f01-406ce9823ac6.jpg)

**Comment by HazAT** [comment]
It's used for both 😅
Ideally, this should never occur but shield.io sometimes is very flakey, the second request is usually cached and almost instant.
Closing this since I do not really want to add a new option just for this "rare" case.
