### ISSUE TITLE
Badge_gravity not working

### ISSUE THREAD

**Issue by ploureiro** [HazAT/badge#71]
Hello I tried to change the badge gravity and it always fail: 

Here is the input:

`badge  --badge_gravity "South" --verbose`

Output:
 

> Error setting value 'South' for option 'badge_gravity'
> /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:222:in `rescue in valid?': [!] wrong number of arguments (given 0, expected 1) (FastlaneCore::Interface::FastlaneError)
> 	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:218:in `valid?'
> 	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:180:in `verify!'
> 	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:87:in `block in verify_value_exists'
> 	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:82:in `each'
> 	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:82:in `verify_value_exists'
> 	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:66:in `initialize'
> 	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:36:in `new'
> 	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:36:in `create'
> 	from /Library/Ruby/Gems/2.3.0/gems/badge-0.9.0/lib/badge/commands_generator.rb:33:in `block (2 levels) in run'
> 	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
> 	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
> 	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
> 	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.89.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
> 	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
> 	from /Library/Ruby/Gems/2.3.0/gems/badge-0.9.0/lib/badge/commands_generator.rb:39:in `run'
> 	from /Library/Ruby/Gems/2.3.0/gems/badge-0.9.0/lib/badge/commands_generator.rb:11:in `start'
> 	from /Library/Ruby/Gems/2.3.0/gems/badge-0.9.0/bin/badge:7:in `<top (required)>'
> 	from /usr/local/bin/badge:22:in `load'
> 	from /usr/local/bin/badge:22:in `<main>'

The same always happens with any gravity orientation.

Fastlane Version: **fastlane-plugin-badge      | 1.1.0   | add_badge**
Badge version: **0.9.0**

**Comment by HazAT** [comment]
cc @giginet

**Comment by giginet** [comment]
So sorry. this is my blame 😭 
I submitted a hotfix.
https://github.com/HazAT/badge/pull/72 

Or you can just revert #69.

**Comment by ploureiro** [comment]
Works like a charm! 🎉 
-->thank's a lot for a so quick fix! 🙌

You can close this issue once #72 is merged!
