### ISSUE TITLE
How to completely remove badge (and shield) and return back to original icons?

### ISSUE THREAD

**Issue by creati8e** [HazAT/badge#76]
Or is there an option to copy modified files? So i would be able to use different icons for debug and production builds

**Comment by creati8e** [comment]
Or is there an option to copy modified files? So i would be able to use different icons for debug and production builds

**Comment by buguibu** [comment]
I guess there is no built in option for that, what i'm doing is:

1. rollback to original icons
2. keep using badge as usual
3. after build and release process gets done and before commiting build changes to repo i do something like this:
`reset_git_repo(
  force: true,
  files: [
    "./resources/Assets.xcassets/Appicon.appiconset/"
  ]
)`

**Comment by creati8e** [comment]
@buguibu simplify your life! I've create a plugin that fits this gap: https://github.com/CleverPumpkin/App-Badge

**Comment by buguibu** [comment]
@creati8e ouch! i'm working on iOS but will tell to my Android coworker. Thanks anyway.

**Comment by HazAT** [comment]
I am closing this since this plugin is made to be used either on a CI or with CVS in place where you can revert your changes.
It's not an actual bug and I don't really want to maintain this as a feature.

**Comment by rainedAllNight** [comment]
> @buguibu simplify your life! I've create a plugin that fits this gap: https://github.com/CleverPumpkin/App-Badge

Will this plan work for iOS?
