### ISSUE TITLE
Cannot remove the "BETA" label with the no_badge property.

### ISSUE THREAD

**Issue by razvangazi** [HazAT/badge#79]
So I'm talking about:

"Add --no_badge as an option to hide the beta badge completely if you just want to add a shield." It does not work for me.

I tried this on a iOS app iOS v11.4. 

Does anyone know how to fix this issue? Sorry if I forgot to mention some details, I'm not an iOS developer..

Thank you,

Raz

**Comment by HazAT** [comment]
This should work, make sure to reset the files since one badge added something as an overlay to your image it stays there. Use `git checkout .`

**Comment by razvangazi** [comment]
> This should work, make sure to reset the files since one badge added something as an overlay to your image it stays there. Use `git checkout .`

This worked, thank you very much !
