### ISSUE TITLE
--badge_gravity not working

### ISSUE THREAD

**Issue by joh-klein** [HazAT/badge#80]
I just installed the current version 0.9.1 and can not for the life of me get "--badge_gravity" to work. I can see, that the argument is taken. But the icon still has the badge on the SouthEast corner, no matter which corner I specify. 

Any ideas?

**Comment by HazAT** [comment]
I just tried it with 
`ruby bin/badge --no_badge --glob "/assets/icon175x175_fitrack.png" --shield "Version-0.0.3-blue" --shield_gravity South`
and it worked perfectly fine.
You can run this command when you clone this repo.

Please provide a repro case for this.

**Comment by akhenda** [comment]
`--badge_gravity` also not working for me but `--shield_gravity` is working.
