### ISSUE TITLE
Ability to change badge text

### ISSUE THREAD

**Issue by Pranit-Harekar** [HazAT/badge#84]
I was wondering if we can change the badge text. Like instead of alpha/beta I would like to add "unstable" badge, so how can I do that?

**Comment by HazAT** [comment]
I will not add this since there are literally unlimited possibilities, instead, you just can pass your custom image see readme:
`badge --custom "path_to/custom_badge.png"`

**Comment by rares-lupascu** [comment]
too bad ... i now need to find or create image just because I want the text to say: "dev" / "staging" ... again ... too bad ... since I assume it is only a matter of excepting a param for the text

**Comment by alexookah** [comment]
@rares-lupascu 
At least you could provide us a template photoshop file for photoshop to change the text
