### ISSUE TITLE
Failed to add badges

### ISSUE THREAD

**Issue by guthyerrz** [HazAT/badge#88]
All of a sudden Jenkins builds that worked perfectly all of a sudden started to return this error wile adding badges to icons

[09:44:13]: Error validating image from shields.io. Use --verbose for more info
[09:44:13]: Waiting for 10s and retry to load image from shields.io tries remaining: 10

Did something change in the shields.io website?

**Comment by koji12000** [comment]
The same problem happened in my environment.
Accessing png url of badge, another url will be redirected.

- png url
  - https://img.shields.io/badge/4.0.6.QA-STG.103-blue.png
- redirect url
  - https://raster.shields.io/badge/4.0.6.QA-STG.103-blue.png

It seems that redirect doesn't work.

**Comment by liamnichols** [comment]
Resolved in #38

**Comment by liamnichols** [comment]
Another solution is to install the additional dependencies in order to use svg images that download from a direct source without redirects.. On your machine just run 

```sh
brew install librsvg
```

As a bonus, you'll get better quality shields also

**Comment by tijs** [comment]
Created a PR to replace the URL with the alternate mentioned in https://github.com/HazAT/badge/pull/87 The fix added to master recently did not help to fix this issue for us.

**Comment by tijs** [comment]
> Another solution is to install the additional dependencies in order to use svg images that download > from a direct source without redirects.

This method also did not work for us i'm afraid, the needed libs could not be found after compiling librsvg on a build machine.

**Comment by Zaszczyk** [comment]
I have this same problem.

**Comment by HazAT** [comment]
Should be fixed in `0.11.0`
