### ISSUE TITLE
Remove 'fastlane' as a runtime dependency in badge.gemspec

### ISSUE THREAD

**Issue by liamnichols** [HazAT/badge#97]
As per #36 and fastlane/fastlane/issues/7412, the `badge` gemspec should not have a dependency on `fastlane` since this causes a dependency cycle when requiring the fastlane-plugin-badge plugin. 

For most people, this goes unnoticed, but in my particular case the `fastlane` gem now has a dependency on `aws-core` and so does another plugin of mine and this causes bundler to get into an infinite loop trying to resolve things. 

Looking at the current plugin template:

https://github.com/fastlane/fastlane/blob/1a79353a6d918eddca61274e97962a5f2770210e/fastlane/lib/fastlane/plugins/template/%25gem_name%25.gemspec.erb#L21-L22

There is a comment explaining not do add `fastlane` as a dependency and it is in fact added as a `development_dependency`

**Comment by HazAT** [comment]
See https://github.com/HazAT/badge/pull/98#issuecomment-1031413213
